### ISSUE TITLE
2021/04/16の作業目標

### ISSUE THREAD

**Issue by iceNori** [yumemi-inc/ios-training#10]
## 目標
- YumemiWeatherのインストール
- session1からsession5までの課題を行う

**Comment by daichikuwa0618** [comment]
@iceNori 

こちらの issue は @iceNori 様個人的な issue でしょうか？

もし `YumemiWeather` やドキュメントの不備であれば issue や Pull-request 大歓迎なのですが、個人的なものであれば https://github.com/yumemi-inc/ios-training#研修の進め方 にあるように、まずはご自身の作業用リポジトリを作成いただき、そちらで管理頂けますと幸いです。

お手数ですが、ご確認お願い致します 🙇

**Comment by iceNori** [comment]
Daichi Hayashi様

大変申し訳ありませんでした。
作成場所を間違えました。

削除いたします。

2021年4月16日(金) 10:50 Daichi Hayashi ***@***.***>:

**Comment by daichikuwa0618** [comment]
@iceNori 

Close 頂いて大丈夫です！
