### ISSUE TITLE
ドキュメントコメントでコードブロックは` ```` `で囲む

### ISSUE THREAD

**Issue by novr** [yumemi-inc/ios-training#24]
ドキュメントコメントでコードブロックは` ```` `で囲む
https://developer.apple.com/library/archive/documentation/Xcode/Reference/xcode_markup_formatting_ref/CodeBlocks.html#//apple_ref/doc/uid/TP40016497-CH12-SW1

既存のコメントも修正となるので一旦issueにします

_Originally posted by @novr in https://github.com/yumemi-inc/ios-training/pull/23#discussion_r847308382_

**Comment by ykws** [comment]
#32 にて対応済み
