### ISSUE TITLE
fetchWeatherList()の引数areaは第一字が大文字でないと正常に値を返さない。

### ISSUE THREAD

**Issue by Kota1021** [yumemi-inc/ios-training#49]
# 課題
[API Reference](https://yumemi-inc.github.io/ios-training/documentation/yumemiweather/yumemiweather/fetchweatherlist(_:))によると、

> API に請求する JSON 文字列の例：
``` 
{
     "areas": ["tokyo"],
     "date": "2020-04-01T12:00:00+09:00"
}
```
> 返された AreaResponse の JSON 文字列の例
``` 
[
    {
        "area": "Tokyo",
        "info": {
            "max_temperature": 25,
            "date": "2020-04-01T12:00:00+09:00",
            "min_temperature": 7,
            "weather_condition": "cloudy"
        }
    }
]
``` 
実際の実装は以下。

```
    static func fetchWeatherList(_ jsonString: String) throws -> String {
        ...
        let areas = request.areas.isEmpty ? Area.allCases : request.areas.compactMap { Area(rawValue: $0) }
        ...
    }
```
そして`Area`は以下の通り
```
public enum Area: String, CaseIterable, Codable {
    case Sapporo
    case Sendai
    case Niigata
    case Kanazawa
    case Tokyo
    case Nagoya
    case Osaka
    case Hiroshima
    case Kochi
    case Fukuoka
    case Kagoshima
    case Naha
}
```

だからfetchWeatherList()に与えるJSONは以下のようにAreasの各要素の1文字目を大文字にすると動作するが、そうしないと動作しない。
``` 
{
     "areas": ["Tokyo"],
     "date": "2020-04-01T12:00:00+09:00"
}
```

# 解決策（案）
```
extension String {
    func upperCaseFirst() -> String{
        guard let firstChar = self.first else { return "" }
        return firstChar.uppercased() + self.dropFirst().lowercased()
    }
}
```
```
 ...
 let areas = request.areas.isEmpty ? Area.allCases : request.areas.compactMap { Area(rawValue: $0.upperCaseFirst()) }
 ...
```

**Comment by Lumisilk** [comment]
直接 push じゃなくて、自分のアカウントに fork して、fork した repo に自分で作ったブランチに切って修正を push してから、そのブランチからこの repo への Pull Request を提出する、というのが OSS に貢献する一般的な方法です。

私も権限ないので…

**Comment by Kota1021** [comment]
forkした自分のリポジトリにpushするんですね！
基礎的な知識を詳細に教えていただきありがとうございます🙇‍♂️
金曜日に実施します

**Comment by es-kumagai** [comment]
次の話題は本件とは根本が別の問題ではありますけれど、列挙型の文字列表現に関係する話題でもあるので投げかけておいてみますね。今回の問題修正に絡めなくても障りはないです。

#### 本題

`Area` 列挙型の列挙子がキャピタルケースになっているのも気になるところで、[Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/#naming:~:text=Follow%20case%20conventions.) に則るとしたら、各列挙子をローワーキャメルケースで扱うのも自然です。それを踏まえると列挙子の名前をそれで統一した上で、当該箇所を `Area(rawValue: $0.lowercased())` にする案もあるかもしれません。

Swift API Design Guidelines は指標なので必ずしも則する必要はないですけれど、こちらのコードでデザインガイドラインから敢えて外す必要もなさそうですし、ガイドラインに即していないのも影響したものと想定して、本件の修正候補として検討してみても良いかもしれない印象でした。

**Comment by novr** [comment]
schemeとhost以外は大文字と小文字が区別されるもの（[RFC3986](https://datatracker.ietf.org/doc/html/rfc3986#section-6.2.2.1)
よってAPI ReferenceのtypoなのでA案のドキュメント修正が妥当かと思います

**Comment by ykws** [comment]
fixes #54
