### ISSUE TITLE
[Session1]気になったこと

### ISSUE THREAD

**Issue by uhooi** [yumemi-inc/ios-training#8]
[Session1](https://github.com/yumemi-inc/ios-training/blob/main/Documentation/AutoLayout.md) で気になったことを共有します。
細かいことなのでそっ閉じしても構いません。
また他に報告する場や模範解答があれば教えていただけると嬉しいです。

- UIImageView と UILabel にマージンがあるように見える  
「UIImageViewとUILabelの隙間はあけない」と書かれていますが、隙間があるように見えます。  
ラベルのテキストサイズをデフォルトから変えているのでしょうか？
- ラベルの文言が小さ過ぎて読めない  
ラベルの文言が小さくて読めないので、なんて書いてあるか知りたいです。
- ラベルの正確な色がわからない  
「赤字」と「青字」しか書かれていないので、正確な色が知りたいです。  
わからないので「System Red Color」と「AccentColor」を指定しています。

|参考: 私のレイアウト|
|:--:|
|<img width="463" alt="スクリーンショット 2021-04-08 18 47 02" src="https://user-images.githubusercontent.com/21194714/114005794-dd4b0980-989a-11eb-95f7-9877b6d9160e.png">|

**Comment by watanavex** [comment]
@uhooi 
鋭いご指摘、ありがとうございます！

気になったことはissueを挙げていただいても構いませんし、PRを出していただいても構いません！
そのあたりも明記したほうが良さそうですね。

> UIImageView と UILabel にマージンがあるように見える
「UIImageViewとUILabelの隙間はあけない」と書かれていますが、隙間があるように見えます。
ラベルのテキストサイズをデフォルトから変えているのでしょうか？

ハイフンだからじゃないでしょうか！ `--` ← これ


> ラベルの文言が小さ過ぎて読めない
ラベルの文言が小さくて読めないので、なんて書いてあるか知りたいです。

ハイフン `--` でした。この辺りを明記すれば、疑問に思われるケースは減るでしょうか 🤔 

> ラベルの正確な色がわからない
「赤字」と「青字」しか書かれていないので、正確な色が知りたいです。
わからないので「System Red Color」と「AccentColor」を指定しています。

確かに！具体的な指定をする方が良さそうですね！

**Comment by uhooi** [comment]
@watanavex 
ご返信ありがとうございますー！
Issue や PR 歓迎の旨、承知しました :)

あ、ハイフンだったのですね！
文字が潰れていて読めないのかと思っていましたｗ

おかげさまで Session1 は（おそらく）できました！
<img width="470" alt="スクリーンショット 2021-04-08 18 52 24" src="https://user-images.githubusercontent.com/21194714/114006869-c5c05080-989b-11eb-99f3-cc3a3fe66394.png">

**Comment by watanavex** [comment]
編集内容を色々と検討しましたが、
研修者の判断に委ねる部分が以降のSessionでも多いため、ここでは特に明記しないことにします。
一般公開したこともあり、今後いろいろな意見を頂いたらそのときまた検討いたします。

**Comment by uhooi** [comment]
ご返信ありがとうございます！
承知しました。
